name: syncer

on:
  push:
    branches:
      - main
  schedule: # Triggers the workflow every day at midnight
    - cron: "0 0 * * *"

jobs:
  syncer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Download image-syncer
        run: |
          bash ./hack/download.sh "${SYNCER_VERSION}"
        env:
          SYNCER_VERSION: ${{ vars.SYNCER_VERSION || 'latest' }}
      - name: Run image-syncer
        run: |
          ./image-syncer --proc=5 --auth=./auth.yaml --images=./images.yaml --retries=3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VOLC_USERNAME: ${{ secrets.VOLC_USERNAME }}
          VOLC_PASSWD: ${{ secrets.VOLC_PASSWD }}
      - name: Failure Slack Notification
        if: failure()
        id: slack-failure
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "${{ secrets.SLACK_BOT_FAILURE_CHANNEL }}"
          slack-message: "❌ Main-Release failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
